default_platform(:ios)

# Parameters
APP_IDENTIFIER = "com.john.FastTracker" # Bundle identifier
APP_NAME = "FastTrackerNewV"            # Application name
SCHEME = "FastTracker"                  # Scheme name
LANGUAGE = "English"                    # Metadata language
KEY_ID = "D6F8LJH486"                   # App Store Connect API Key
ISSUER_ID = "8f309cb4-1beb-4667-b6f9-70dd00918215" # Issuer ID
KEY_FILEPATH = "./fastlane/AuthKey_#{KEY_ID}.p8"   # Keypath
OUTPUT_DIR = "./build"                  # IPA path
OUTPUT_NAME = "FastTracker.ipa"         # IPA name
EXPORT_METHOD = "app-store"             # Export type

platform :ios do
  lane :appcreate do
    produce(
      app_identifier: APP_IDENTIFIER,
      app_name: APP_NAME,
      language: LANGUAGE,
      skip_itc: false,            # Submit to App Store Connect
      skip_devcenter: false       # Submit to Developer Portal
    )
    UI.success("Application created in AppStoreConnect")
  end

  lane :certificates do 
    match(type: "appstore")
  end

  lane :build do
    gym(
      scheme: SCHEME,
      export_method: EXPORT_METHOD, 
      clean: true,             
      project: "./FastTracker.xcodeproj",
      output_directory: OUTPUT_DIR, 
      output_name: OUTPUT_NAME,
      verbose: true,
      export_options: {
        provisioningProfiles: {
          "com.john.FastTracker" => "match AppStore com.john.FastTracker"
        }
      }                 # Turn on detailed logs
    )
    UI.success("The build was completed successfully")
  end

  lane :deploy do
    deliver(
      api_key: app_store_connect_api_key(
        key_id: KEY_ID,
        issuer_id: ISSUER_ID,
        key_filepath: KEY_FILEPATH
      ),
      precheck_include_in_app_purchases: false,
      skip_metadata: true,      
      skip_screenshots: true,   
      submit_for_review: false  
    )
    UI.success("✅ Завантаження до App Store Connect завершено")
  end
end
